-- vim.keymap.set("n","B","<cmd>!make<cr>",{silent = true, buffer = true})
-- vim.keymap.set("n","<leader>i","<cmd>lua require('screenshot.screenshot').latexTakeShotAndSave()<cr>",{silent = true, buffer = true})
vim.keymap.set({"n"},"<leader>i",function(  )
    require("screenshot.screenshot").latexTakeShotAndSave()
end,{buffer=true,silent=true})
vim.keymap.set({"i"},"<A-i>",function(  )
    require("screenshot.screenshot").latexTakeShotAndSave()
end,{buffer=true,silent=true})
vim.keymap.set({"n"},"<leader>t",function(  )
    vim.cmd("VimtexCompile")
end,{buffer=true,silent=true})
